version: 1.2
workflows:
  - subclass: Galaxy
    primaryDescriptorPath: /histological-staining-area-quantification.ga
    testParameterFiles:
      - /histological-staining-area-quantification-test.yml
    name: histological-staining-area-quantification
    authors:
      - name: Diana Chiang Jurado
        orcid: 0000-0002-5857-1477