version: 1.2
workflows:
- name: COVID-19-PE-ARTIC-ILLUMINA
  subclass: Galaxy
  testParameterFiles:
  - /pe-artic-variation-test.ym
  publish: true
  primaryDescriptorPath: /pe-artic-variation.ga
  authors:
  - name: Wolfgang Maier
    orcid: 0000-0002-9464-6640
