version: 1.2
workflows:
- name: 'COVID-19-PE-ARTIC-ILLUMINA'
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /pe-artic-variation.ga
  testParameterFiles:
  - /pe-artic-variation-tests.yml
  authors:
  - name: Wolfgang Maier
    orcid: 0000-0002-9464-6640
