version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /pox-virus-half-genome.ga
  testParameterFiles:
  - /pox-virus-half-genome-tests.yml
  authors:
  - name: Viktoria Isabel Schwarz
    orcid: 0000-0001-6897-1215
  - name: Wolfgang Maier
    orcid: 0000-0002-9464-6640
