version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /chipseq-pe-with-replicates-controls.ga
  testParameterFiles:
  - /chipseq-pe-with-replicates-controls-tests.yml
  authors:
  - name: Wolfgang Maier
    orcid: 0000-0002-9464-6640
