version: 1.2
workflows:
- name: IIa-denoising-se
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /QIIME2-IIa-denoising-and-feature-table-creation-single-end.ga
  testParameterFiles:
  - /QIIME2-IIa-denoising-and-feature-table-creation-single-end-tests.yml
  authors:
  - name: Debjyoti Ghosh
    orcid: 0009-0008-1496-1677
  - name: "Helmholtz-Zentrum für Umweltforschung - UFZ"
    address: "Permoserstraße 15, 04318 Leipzig"
- name: IIb-denoising-pe
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /QIIME2-IIb-denoising-and-feature-table-creation-paired-end.ga
  testParameterFiles:
  - /QIIME2-IIb-denoising-and-feature-table-creation-paired-end-tests.yml
  authors:
  - name: Debjyoti Ghosh
    orcid: 0009-0008-1496-1677
  - name: "Helmholtz-Zentrum für Umweltforschung - UFZ"
    address: "Permoserstraße 15, 04318 Leipzig"
