version: 1.2
workflows:
- name: pggb-pangenome-build
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /pggb-pangenome-build.ga
  testParameterFiles:
  - /pggb-pangenome-build-tests.yml
  authors:
  - name: Anton Nekrutenko
    orcid: 0000-0002-5987-8032
