version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /host-or-contamination-removal-on-short-reads.ga
  testParameterFiles:
  - /host-or-contamination-removal-on-short-reads-tests.yml
  authors:
  - name: Paul Zierep
    orcid: 0000-0003-2982-388X
  - name: "B\xE9r\xE9nice Batut"
    orcid: 0000-0001-9852-1987
