version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /viral-detection-from-bulk-metagenomes.ga
  testParameterFiles:
  - /viral-detection-from-bulk-metagenomes-test.yml
  authors:
  - name: Mina Hojat Ansari
    orcid: 0000-0002-3602-7884
  - name: "Niklas Stahl"
