version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /atacseq.ga
  testParameterFiles:
  - /atacseq-tests.yml
  authors:
  - name: Lucille Delisle
    orcid: 0000-0002-1964-4960
