version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /metagenomic-taxonomy-profiling.ga
  testParameterFiles:
  - /metagenomic-taxonomy-profiling.yml
  authors:
  - name: Engy Nasr
    orcid: 0000-0001-9047-4215
    url: https://orcid.org/0000-0001-9047-4215
  - name: "Bérénice Batut"
    orcid: 0000-0001-9852-1987
    url: https://orcid.org/0000-0001-9852-1987
  - name: Paul Zierep
    orcid: 0000-0003-2982-388X
    url: https://orcid.org/0000-0003-2982-388X
  - name: "G\xE9raldine Piot"
  - name: Mina Hojat Ansari
    orcid: 0000-0002-3602-7884
  - name: AuBi (Auvergne Bioinformatique)
    url: https://mesocentre.uca.fr/projets-associes/plateforme-aubi