version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /Scaffolding-HiC-VGP8.ga
  testParameterFiles:
  - /Scaffolding-HiC-VGP8-tests.yml
  authors:
  - name: VGP
    url: https://vertebrategenomeproject.org
  - name: Galaxy
