version: 1.2
workflows:
- name: main
  primaryDescriptorPath: /Generic-variation-analysis-reporting.ga
  subclass: Galaxy
  testParameterFiles:
  - /Generic-variation-analysis-reporting-tests.yml
  publish: true
