version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /Generic-variation-analysis-reporting.ga
  testParameterFiles:
  - /Generic-variation-analysis-reporting-tests.yml
  authors:
  - name: Wolfgang Maier
    orcid: 0000-0002-9464-6640
