version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /Functional_annotation_of_protein_sequences.ga
  testParameterFiles:
  - /Functional_annotation_of_protein_sequences-tests.yml
  authors:
  - name: Romane Libouban
    email: romane.libouban@irisa.fr
    orcid: 0009-0001-4920-9951
  - name: Anthony Bretaudeau
    email: anthony.bretaudeau@irisa.fr
    orcid: 0000-0003-0914-2470
