version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /fragment-based-docking-scoring.ga
  testParameterFiles:
  - /fragment-based-docking-scoring-tests.yml
  authors:
  - name: Simon Bray
    identifier: 0000-0002-0621-6705
  - name: Tim Dudgeon
    identifier: 0000-0001-6879-5194
