version: 1.2
workflows:
- name: rna-variant-discovery
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /RNAvar.ga
  testParameterFiles:
  - /RNAvar-tests.yml
  authors:
  - name: "Emre Gülben"
    orcid: 0009-0009-9085-1055
  - name: "Lucille Delisle"
    orcid: 0000-0002-1964-4960