version: 1.2
workflows:
- name: rna-variant-discovery
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /RNAvar.ga
  testParameterFiles:
  - /RNAvar-tests.yml
  authors:
  - name: "Emre Gülben"
    orcid: "https://orcid.org/0009-0009-9085-1055"
