version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /kmindex-logan-sra-retrieval.ga
  testParameterFiles:
  - /kmindex-logan-sra-retrieval-tests.yml
  authors:
  - name: Danielle Callan
    orcid: 0009-0009-3690-8372
