version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /Mass_spectrometry__LC-MS_preprocessing_with_XCMS.ga
  testParameterFiles:
  - /Mass_spectrometry__LC-MS_preprocessing_with_XCMS-tests.yml
  authors:
  - name: workflow4metabolomics
    image: https://raw.githubusercontent.com/workflow4metabolomics/workflow4metabolomics/master/images/logo/logo_w4m-0.1-black-orange.png
    url: https://workflow4metabolomics.org
