version: 1.2
workflows:
- name: Split_collection_using_tabular
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /Split_collection_using_tabular.ga
  testParameterFiles:
  - /Split_collection_using_tabular-tests.yml
  authors:
  - name: Lucille Delisle
    orcid: 0000-0002-1964-4960
- name: Split_collection_using_comma_separated_list
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /Split_collection_using_comma_separated_list.ga
  testParameterFiles:
  - /Split_collection_using_comma_separated_list-tests.yml
  authors:
  - name: Lucille Delisle
    orcid: 0000-0002-1964-4960
- name: Split_collection_by_pattern_in_identifiers
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /Split_collection_by_pattern_in_identifiers.ga
  testParameterFiles:
  - /Split_collection_by_pattern_in_identifiers-tests.yml
  authors:
  - name: Lucille Delisle
    orcid: 0000-0002-1964-4960
