version: 1.2
workflows:
- name: Split-collection-by-pattern-in-identifiers
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /Split-collection-by-pattern-in-identifiers.ga
  testParameterFiles:
  - /Split-collection-by-pattern-in-identifiers-tests.yml
  authors:
  - name: Lucille Delisle
    orcid: 0000-0002-1964-4960
- name: Split-collection-using-tabular
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /Split-collection-using-tabular.ga
  testParameterFiles:
  - /Split-collection-using-tabular-tests.yml
  authors:
  - name: Lucille Delisle
    orcid: 0000-0002-1964-4960
- name: Split-collection-using-comma-separated-list
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /Split-collection-using-comma-separated-list.ga
  testParameterFiles:
  - /Split-collection-using-comma-separated-list-tests.yml
  authors:
  - name: Lucille Delisle
    orcid: 0000-0002-1964-4960
