version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /qsrr-modeling.ga
  testParameterFiles:
  - /qsrr-modeling.yml
  authors:
  - name: Helge Hecht
    orcid: https://orcid.org/0000-0001-6744-996X
  - name: RECETOX
  - name: ELIXIR Metabolomics Community
