version: 1.5.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /tb-variant-analysis.ga
  testParameterFiles:
  - /tb-variant-analysis-tests.yml
  authors:
  - name: Peter van Heusden
    alternateName: pvanheus
    orcid: 0000-0001-6553-5274
    affiliation: South African National Bioinformatics Institute, University of the Western Cape
    email: pvanheusden@uwc.ac.za
  - name: South African National Bioinformatics Institute, University of the Western Cape
    url: https://sanbi.ac.za

