version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /mgnify-amplicon-pipeline-v5-quality-control-paired-end.ga
  testParameterFiles:
  - /mgnify-amplicon-pipeline-v5-quality-control-paired-end-tests.yml
  authors:
  - name: Rand Zoabi
    orcid: 0009-0000-2501-8053
  - name: Paul Zierep
    orcid: 0000-0003-2982-388X
  - name: EMBL's European Bioinformatics Institute
    url: https://www.ebi.ac.uk/metagenomics
