version: 1.2
workflows:
- name: scrna-seq-fastq-to-matrix-10x-cellplex
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /scrna-seq-fastq-to-matrix-10x-cellplex.ga
  testParameterFiles:
  - /scrna-seq-fastq-to-matrix-10x-cellplex-tests.yml
  authors:
  - name: Lucille Delisle
    orcid: 0000-0002-1964-4960
  - name: Mehmet Tekman
    orcid: 0000-0002-4181-2676
  - name: Hans-Rudolf Hotz
    orcid: 0000-0002-2799-424X
  - name: Daniel Blankenberg
    orcid: 0000-0002-6833-9049
  - name: Wendi Bacon
    orcid: 0000-0002-8170-8806
- name: scrna-seq-fastq-to-matrix-10x-v3
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /scrna-seq-fastq-to-matrix-10x-v3.ga
  testParameterFiles:
  - /scrna-seq-fastq-to-matrix-10x-v3-tests.yml
  authors:
  - name: Lucille Delisle
    orcid: 0000-0002-1964-4960
  - name: Mehmet Tekman
    orcid: 0000-0002-4181-2676
  - name: Hans-Rudolf Hotz
    orcid: 0000-0002-2799-424X
  - name: Daniel Blankenberg
    orcid: 0000-0002-6833-9049
  - name: Wendi Bacon
    orcid: 0000-0002-8170-8806
