version: 1.2
workflows:
- name: 'COVID-19-VARIATION-REPORTING'
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /variation-reporting.ga
  testParameterFiles:
  - /variation-reporting-tests.yml
  authors:
  - name: Wolfgang Maier
    orcid: 0000-0002-9464-6640
