version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /Simple-variant-calling-for-diploid-taxa.ga
  testParameterFiles:
  - /Simple-variant-calling-for-diploid-taxa-tests.yml
  authors:
  - name: Anton Nekrutenko
    orcid: 0000-0002-5987-8032
