version: 1.2
workflows:
- name: correlation-of-samples-on-peaks
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /correlation-of-samples-on-peaks.ga
  testParameterFiles:
  - /correlation-of-samples-on-peaks-tests.yml
  authors:
  - name: Lucille Delisle
    orcid: 0000-0002-1964-4960
  - name: Alexandre Mayran
    orcid: 0000-0002-1228-0308
  - name: Olusegun E. Adebayo
    orcid: 0009-0003-9444-3944
