version: 1.2
workflows:
- name: 'COVID-19-CONSENSUS-CONSTRUCTION'
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /consensus-from-variation.ga
  testParameterFiles:
  - /consensus-from-variation-tests.yml
  authors:
  - name: Wolfgang Maier
    orcid: 0000-0002-9464-6640
