name: Periodic workflow test
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  setup:
    name: Setup cache
    uses: galaxyproject/iwc/.github/workflows/setup.yml@main
    with:
      python-version-list: "[\"3.7\"]"
      galaxy-fork: galaxyproject
      galaxy-branch: master
  test:
    name: Test workflow
    needs: setup
    uses: galaxyproject/iwc/.github/workflows/test_workflows.yml@main
    with:
      galaxy-head-sha: ${{ needs.setup.outputs.galaxy-head-sha }}
      python-version-list: "[\"3.7\"]"
      galaxy-fork: galaxyproject
      galaxy-branch: master
      repository-list: '.'
      check-outputs: true
