version: 1.2
workflows:
- name: FAIRyMAGs-binning-evaluation
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /FAIRyMAGs-binning-evaluation.ga
  testParameterFiles:
  - /FAIRyMAGs-binning-evaluation-tests.yml
  authors:
  - name: Santino Faack
    orcid: 0009-0004-0382-2023
