version: 1.2
workflows:
- name: Convert-Optional-Input-Text-to-Boolean
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /Convert-Optional-Input-Text-to-Boolean.ga
  testParameterFiles:
  - /Convert-Optional-Input-Text-to-Boolean-tests.yml
  authors:
  - name: Niklas Mayle
    orcid: 0009-0009-0059-1887
- name: Convert-Optional-Input-Dataset-to-Boolean
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /Convert-Optional-Input-Dataset-to-Boolean.ga
  testParameterFiles:
  - /Convert-Optional-Input-Dataset-to-Boolean-tests.yml
  authors:
  - name: Niklas Mayle
    orcid: 0009-0009-0059-1887
- name: Split-BAM-by-Path
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /Split-BAM-by-Path.ga
  testParameterFiles:
  - /Split-BAM-by-Path-tests.yml
  authors:
  - name: Niklas Mayle
    orcid: 0009-0009-0059-1887
- name: Pangenome-Variant-Calling-using-VG-Giraffe-and-Google-DeepVariant
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /Pangenome-Variant-Calling-using-VG-Giraffe-and-Google-DeepVariant.ga
  testParameterFiles:
  - /Pangenome-Variant-Calling-using-VG-Giraffe-and-Google-DeepVariant-tests.yml
  authors:
  - name: Niklas Mayle
    orcid: 0009-0009-0059-1887
  - name: Saim Momin
    orcid: 0009-0003-9935-828X
