version: 1.2
workflows:
- name: main
  primaryDescriptorPath: /metaprosip.ga
  subclass: Galaxy
  testParameterFiles:
  - /metaprosip-tests.yml
  authors:
  - name: Matthias Bernt
    orcid: 0000-0003-3763-0797
