version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /Nanopore-Pre-Processing.ga
  testParameterFiles:
  - /Nanopore-Pre-Processing-tests.yml
  authors:
  - name: "Bérénice Batut"
    orcid: 0000-0001-9852-1987
    url: https://orcid.org/0000-0001-9852-1987
  - name: Engy Nasr
    orcid: 0000-0001-9047-4215
    url: https://orcid.org/0000-0001-9047-4215
  - name: Paul Zierep
    orcid: 0000-0003-2982-388X
    url: https://orcid.org/0000-0003-2982-388X
