version: 1.2
workflows:
- name: aDNA-analysis
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /aDNA-analysis.ga
  testParameterFiles:
  - /aDNA-analysis-tests.yml
  authors:
  - name: Ali Mert AYDIN
    orcid: "https://orcid.org/0009-0008-9038-0815"
