version: 1.2
workflows:
- name: adna-analysis
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /adna-analysis.ga
  testParameterFiles:
  - /adna-analysis-tests.yml
  authors:
  - name: Ali Mert AYDIN
    orcid: "https://orcid.org/0009-0008-9038-0815"
