version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /Taxonomy-Assignment-with-QIIME2.ga
  testParameterFiles:
  - /Taxonomy-Assignment-with-QIIME2-tests.yml
  authors:
  - name: Tristan Reynolds
    orcid: 0000-0002-6606-5953
  - name: Amy Loughman
    orcid: 0000-0002-0257-1443
