version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /filter-a-matrix-by-highly-variable-features.ga
  testParameterFiles:
  - /filter-a-matrix-by-highly-variable-features-tests.yml
  authors:
  - name: Amirhossein Naghsh Nilchi
    orcid: 0000-0003-1329-3044
