version: 1.2
workflows:
- name: SARS-COV-2-ILLUMINA-AMPLICON-IVAR-PANGOLIN-NEXTCLADE
  primaryDescriptorPath: /pe-wgs-ivar-analysis.ga
  subclass: Galaxy
  testParameterFiles:
  - /pe-wgs-ivar-analysis-test.yml
  publish: true
  primaryDescriptorPath: /pe-wgs-ivar-analysis.ga
  authors:
  - name: Peter van Heusden
    orcid: 0000-0001-6553-5274
