version: 1.2
workflows:
- name: 'SARS-COV-2-ILLUMINA-AMPLICON-IVAR-PANGOLIN-NEXTCLADE'
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /pe-wgs-ivar-analysis.ga
  testParameterFiles:
  - /pe-wgs-ivar-analysis-tests.yml
  authors:
  - name: Peter van Heusden
    orcid: 0000-0001-6553-5274
