version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /WW-SARS-CoV-2-lineages-analysis-on-ARTIC-PE-data.ga
  testParameterFiles:
  - /WW-SARS-CoV-2-lineages-analysis-on-ARTIC-PE-data-tests.yml
  authors:
  - name: Polina Polunina
    orcid: 0000-0002-0507-460
  - name: "Bérénice Batut"
    orcid: 0000-0001-9852-198
  - name: Wolfgang Maier
    orcid: 0000-0002-9464-664
