version: 1.2
workflows:
- name: consensus-peaks-chip-sr
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /consensus-peaks-chip-sr.ga
  testParameterFiles:
  - /consensus-peaks-chip-sr-tests.yml
  authors:
  - name: Lucille Delisle
    orcid: 0000-0002-1964-4960
- name: consensus-peaks-chip-pe
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /consensus-peaks-chip-pe.ga
  testParameterFiles:
  - /consensus-peaks-chip-pe-tests.yml
  authors:
  - name: Lucille Delisle
    orcid: 0000-0002-1964-4960
- name: consensus-peaks-atac-cutandrun
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /consensus-peaks-atac-cutandrun.ga
  testParameterFiles:
  - /consensus-peaks-atac-cutandrun-tests.yml
  authors:
  - name: Lucille Delisle
    orcid: 0000-0002-1964-4960
