version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /pyeuk-standard.ga
  testParameterFiles:
  - /pyeuk-standard-tests.yml
  authors:
  - name: Anton Nekrutenko
  - name: Sergei Pond
