version: 0.2.4
workflows:
- name: 'SCXA prod v0.2.4, Scanpy 1.7.X'
  primaryDescriptorPath: /SingleCellExpressionAtlas-smartseq.ga
  subclass: Galaxy
  testParameterFiles:
  - /SingleCellExpressionAtlas-smartseq-test.yml
