version: 1.2
workflows:
- name: COVID-19-PE-WGS-ILLUMINA
  subclass: Galaxy
  testParameterFiles:
  - /pe-wgs-variation-test.yml
  publish: true
  primaryDescriptorPath: /pe-wgs-variation.ga
  authors:
  - name: Wolfgang Maier
    identifier: 0000-0002-9464-6640
