version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /parallel-accession-download.ga
  testParameterFiles:
  - /parallel-accession-download-tests.yml
  authors:
  - name: Marius van den Beek
    orcid: 0000-0002-9676-7032
  - name: IWC
    url: https://github.com/galaxyproject/iwc
