version: 1.2
workflows:
- name: 'SARS-COV-2-ILLUMINA-AMPLICON-IVAR-PANGOLIN-NEXTCLADE'
  primaryDescriptorPath: /pe-wgs-ivar-analysis.ga
  subclass: Galaxy
  testParameterFiles:
  - /pe-wgs-ivar-analysis-test.yml
