version: 1.2
workflows:
- name: hic_juicermediumtabix_to_cool_cooler
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /hic_juicermediumtabix_to_cool_cooler.ga
  testParameterFiles:
  - /hic_juicermediumtabix_to_cool_cooler-tests.yml
  authors:
  - name: Lucille Delisle
    orcid: 0000-0002-1964-4960
- name: hic_fastq_to_cool_hicup_cooler
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /hic_fastq_to_cool_hicup_cooler.ga
  testParameterFiles:
  - /hic_fastq_to_cool_hicup_cooler-tests.yml
  authors:
  - name: Lucille Delisle
    orcid: 0000-0002-1964-4960
- name: chic_fastq_to_cool_hicup_cooler
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /chic_fastq_to_cool_hicup_cooler.ga
  testParameterFiles:
  - /chic_fastq_to_cool_hicup_cooler-tests.yml
  authors:
  - name: Lucille Delisle
    orcid: 0000-0002-1964-4960
- name: hic_fastq_to_pairs_hicup
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /hic_fastq_to_pairs_hicup.ga
  testParameterFiles:
  - /hic_fastq_to_pairs_hicup-tests.yml
  authors:
  - name: Lucille Delisle
    orcid: 0000-0002-1964-4960
