version: 1.2
workflows:
- name: hic-fastq-to-cool-hicup-cooler
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /hic_fastq_to_cool_hicup_cooler.ga
  testParameterFiles:
  - /hic_fastq_to_cool_hicup_cooler-tests.yml
  authors:
  - name: Lucille Delisle
    orcid: 0000-0002-1964-496
- name: chic-fastq-to-cool-hicup-cooler
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /chic_fastq_to_cool_hicup_cooler.ga
  testParameterFiles:
  - /chic_fastq_to_cool_hicup_cooler-tests.yml
  authors:
  - name: Lucille Delisle
    orcid: 0000-0002-1964-496
- name: hic-juicermediumtabix-to-cool-cooler
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /hic_juicermediumtabix_to_cool_cooler.ga
  testParameterFiles:
  - /hic_juicermediumtabix_to_cool_cooler-tests.yml
  authors:
  - name: Lucille Delisle
    orcid: 0000-0002-1964-496
- name: hic-fastq-to-pairs-hicup
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /hic_fastq_to_pairs_hicup.ga
  testParameterFiles:
  - /hic_fastq_to_pairs_hicup-tests.yml
  authors:
  - name: Lucille Delisle
    orcid: 0000-0002-1964-496
