version: 1.2
workflows:
- name: hic-fastq-to-cool-hicup-cooler
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /hic-fastq-to-cool-hicup-cooler.ga
  testParameterFiles:
  - /hic-fastq-to-cool-hicup-cooler-tests.yml
  authors:
  - name: Lucille Delisle
    orcid: 0000-0002-1964-4960
- name: chic-fastq-to-cool-hicup-cooler
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /chic-fastq-to-cool-hicup-cooler.ga
  testParameterFiles:
  - /chic-fastq-to-cool-hicup-cooler-tests.yml
  authors:
  - name: Lucille Delisle
    orcid: 0000-0002-1964-4960
- name: hic-juicermediumtabix-to-cool-cooler
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /hic-juicermediumtabix-to-cool-cooler.ga
  testParameterFiles:
  - /hic-juicermediumtabix-to-cool-cooler-tests.yml
  authors:
  - name: Lucille Delisle
    orcid: 0000-0002-1964-4960
- name: hic-fastq-to-pairs-hicup
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /hic-fastq-to-pairs-hicup.ga
  testParameterFiles:
  - /hic-fastq-to-pairs-hicup-tests.yml
  authors:
  - name: Lucille Delisle
    orcid: 0000-0002-1964-4960
