version: 1.2
workflows:
- name: 'COVID-19-ARTIC-ONT'
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /ont-artic-variation.ga
  testParameterFiles:
  - /ont-artic-variation-tests.yml
  authors:
  - name: Wolfgang Maier
    orcid: 0000-0002-9464-6640
