version: 1.2
workflows:
- name: COVID-19-ARTIC-ONT
  subclass: Galaxy
  testParameterFiles:
  - /ont-artic-variation-test.yml
  publish: true
  primaryDescriptorPath: /ont-artic-variation.ga
  authors:
  - name: Wolfgang Maier
    identifier: 0000-0002-9464-6640
