version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /Extract-eggNOG-mapper-annotation-abundance-tables.ga
  testParameterFiles:
  - /Extract-eggNOG-mapper-annotation-abundance-tables-tests.yml
  authors:
  - name: "B\xE9r\xE9nice Batut"
    orcid: 0000-0001-9852-1987
  - name: FAIRyMAGs consortium
    url: https://github.com/usegalaxy-eu/FAIRyMAGs
