version: 1.2
workflows:
- name: Velocyto-on10X-from-bundled
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /Velocyto-on10X-from-bundled.ga
  testParameterFiles:
  - /Velocyto-on10X-from-bundled-tests.yml
  authors:
  - name: Lucille Delisle
    orcid: 0000-0002-1964-4960
- name: Velocyto-on10X-filtered-barcodes
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /Velocyto-on10X-filtered-barcodes.ga
  testParameterFiles:
  - /Velocyto-on10X-filtered-barcodes-tests.yml
  authors:
  - name: Lucille Delisle
    orcid: 0000-0002-1964-4960
