version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /dna-seq-classification-lstm.ga
  testParameterFiles:
  - /dna-seq-classification-lstm-tests.yml
  authors:
  - name: Anup Kumar
    orcid: 0000-0002-2068-4695
