version: 1.2
workflows:
- name: Pool of amplicons map to reference
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /Map-to-reference.ga
  testParameterFiles:
  - /Map-to-reference-tests.yml
  authors:
  - name: "Mol\xE8ne Mah\xE9"
    identifier: momah
