version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /metaquantome_function_wf.ga
  testParameterFiles:
  - /metaquantome_function_wf-tests.yml
  authors:
  - name: Subina Mehta
    orcid: 0000-0001-9818-0537
  - name: Timothy J. Griffin
    orcid: 0000-0001-6801-2559
  - name: Pratik Jagtap
    orcid: 0000-0003-0984-0973
  - name: Emma Leith
    alternateName: emmaleith
  - name: Marie Crane
    alternateName: mariecrane
  - name: Praveen Kumar
    alternateName: pravs3683
