version: 1.2
workflows:
  - subclass: Galaxy
    primaryDescriptorPath: /Ecoregionalization_workflow_Part_1.ga
    testParameterFiles:
      - /Ecoregionalization_workflow_Part_1-tests.yml
    name: Ecoregionalization-workflow-part-1
    authors:
      - orcid: 0009-0009-5969-8478
  - subclass: Galaxy
    primaryDescriptorPath: /Ecoregionalization_workflow_Part_2.ga
    testParameterFiles:
      - /Ecoregionalization_workflow_Part_2-tests.yml
    name: Ecoregionalization-workflow-part-2
    authors:
      - orcid: 0009-0009-5969-8478
