version: 1.2
workflows:
- name: capheine-core-and-compare
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /capheine-core-and-compare.ga
  testParameterFiles:
  - /capheine-core-and-compare-tests.yml
  authors:
  - name: Danielle Callan
  - name: Hannah Verdonk
  - name: Sergei L. Kosakovsky Pond
- name: hyphy-core
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /hyphy-core.ga
- name: hyphy-compare
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /hyphy-compare.ga
- name: hyphy-preprocessing
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /hyphy-preprocessing.ga
