version: 1.2
workflows:
- name: capheine-core-and-compare
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /capheine-core-and-compare.ga
  testParameterFiles:
  - /capheine-core-and-compare-tests.yml
  authors:
  - name: Danielle Callan
    orcid: 0009-0009-3690-8372
  - name: Hannah Verdonk
    orcid: 0000-0003-1967-4403
  - name: Sergei L. Kosakovsky Pond
    orcid: 0000-0003-4817-4029
- name: hyphy-core
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /hyphy-core.ga
  testParameterFiles:
  - /hyphy-core-tests.yml
  authors:
  - name: Danielle Callan
    orcid: 0009-0009-3690-8372
  - name: Hannah Verdonk
    orcid: 0000-0003-1967-4403
  - name: Sergei L. Kosakovsky Pond
    orcid: 0000-0003-4817-4029
- name: hyphy-compare
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /hyphy-compare.ga
  testParameterFiles:
  - /hyphy-compare-tests.yml
  authors:
  - name: Danielle Callan
    orcid: 0009-0009-3690-8372
  - name: Hannah Verdonk
    orcid: 0000-0003-1967-4403
  - name: Sergei L. Kosakovsky Pond
    orcid: 0000-0003-4817-4029
- name: hyphy-preprocessing
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /hyphy-preprocessing.ga
  testParameterFiles:
  - /hyphy-preprocessing-tests.yml
  authors:
  - name: Danielle Callan
    orcid: 0009-0009-3690-8372
  - name: Hannah Verdonk
    orcid: 0000-0003-1967-4403
  - name: Sergei L. Kosakovsky Pond
    orcid: 0000-0003-4817-4029
