version: 1.2
workflows:
- name: baredSC-1d-logNorm
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /baredSC-1d-logNorm.ga
  testParameterFiles:
  - /baredSC-1d-logNorm-tests.yml
  authors:
  - name: Lucille Delisle
    orcid: 0000-0002-1964-4960
- name: baredSC-2d-logNorm
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /baredSC-2d-logNorm.ga
  testParameterFiles:
  - /baredSC-2d-logNorm-tests.yml
  authors:
  - name: Lucille Delisle
    orcid: 0000-0002-1964-4960
