version: 1.2
workflows:
- name: 'COVID-19-SE-WGS-ILLUMINA'
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /se-wgs-variation.ga
  testParameterFiles:
  - /se-wgs-variation-tests.yml
  authors:
  - name: Wolfgang Maier
    orcid: 0000-0002-9464-6640
