version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /SARS-CoV-2-wastewater-analysis-from-metatranscriptomic-PE-data-with-Freyja.ga
  testParameterFiles:
  - /SARS-CoV-2-wastewater-analysis-from-metatranscriptomic-PE-data-with-Freyja-tests.yml
  authors:
  - name: Polina Polunina
    orcid: 0000-0002-0507-460
  - name: "B\xE9r\xE9nice Batut"
    orcid: 0000-0001-9852-198
  - name: Wolfgang Maier
    orcid: 0000-0002-9464-664
