version: 1.2
workflows:
- name: Annotation of eukaryotic genomes with MAKER
  primaryDescriptorPath: /maker-annotation-eukaryote.ga
  subclass: Galaxy
  testParameterFiles:
  - /maker-annotation-eukaryote.yml
