version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /Assembly-polishing-with-long-reads.ga
  testParameterFiles:
  - /Assembly-polishing-with-long-reads-tests.yml
  authors:
  - name: Anna Syme
    orcid: 0000-0002-9906-0673
