version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /metaproteomics_wf.ga
  testParameterFiles:
  - /metaproteomics_wf-tests.yml
  authors:
  - name: Timothy Griffin
    orcid: 0000-0001-6801-2559
  - name: Pratik Jagtap
    orcid: 0000-0003-0984-0973
  - name: James Johnson
    identifier: https://github.com/jj-umn
  - name: Clemens Blank
    orcid: 0000-0002-1726-2256
  - name: Subina Mehta
    orcid: 0000-0001-9818-0537
