version: 1.2
workflows:
- name: main
  primaryDescriptorPath: /protein-ligand-complex-parameterization.ga
  subclass: Galaxy
  testParameterFiles:
  - /protein-ligand-complex-parameterization-tests.yml
